/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ProductHandleRouteImport } from './routes/product/$handle'
import { Route as ApiPublicCatalogImageNameRouteImport } from './routes/api/public/catalog-image.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogImageNameRoute =
  ApiPublicCatalogImageNameRouteImport.update({
    id: '/api/public/catalog-image/$name',
    path: '/api/public/catalog-image/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/collections': typeof CollectionsRoute
  '/unlock': typeof UnlockRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/catalog-image/$name': typeof ApiPublicCatalogImageNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/collections': typeof CollectionsRoute
  '/unlock': typeof UnlockRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/catalog-image/$name': typeof ApiPublicCatalogImageNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/collections': typeof CollectionsRoute
  '/unlock': typeof UnlockRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/catalog-image/$name': typeof ApiPublicCatalogImageNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/collections'
    | '/unlock'
    | '/product/$handle'
    | '/api/public/catalog-image/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/collections'
    | '/unlock'
    | '/product/$handle'
    | '/api/public/catalog-image/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/collections'
    | '/unlock'
    | '/product/$handle'
    | '/api/public/catalog-image/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CollectionsRoute: typeof CollectionsRoute
  UnlockRoute: typeof UnlockRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ApiPublicCatalogImageNameRoute: typeof ApiPublicCatalogImageNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog-image/$name': {
      id: '/api/public/catalog-image/$name'
      path: '/api/public/catalog-image/$name'
      fullPath: '/api/public/catalog-image/$name'
      preLoaderRoute: typeof ApiPublicCatalogImageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CollectionsRoute: CollectionsRoute,
  UnlockRoute: UnlockRoute,
  ProductHandleRoute: ProductHandleRoute,
  ApiPublicCatalogImageNameRoute: ApiPublicCatalogImageNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
